# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeakingTimer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'SwiftySound'
    pod 'Hero'

  # Pods for SpeakingTimer

  target 'SpeakingTimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpeakingTimerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SpeakingTimerWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeakingTimerWatch

end

target 'SpeakingTimerWatch Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpeakingTimerWatch Extension

end
